### ISSUE TITLE
Create a Token Approvals app

### ISSUE THREAD

**Issue by gabmontes** [purefinance/pure.finance#12]
### User story:

- [x] A user 0x1234 gives infinite approval to external address (e.g. Vesper pool) 0x567 for token 0x890a to i.e. reduce the gas costs associated with allowances.

### Nice to haves:

- [x] Give limited approval.
- [x] Revoke approvals.
- [x] Enter token by symbol.
- [x] Enter external address by ENS or curated list.

**Comment by jgarzik** [comment]
Nice to have:  list approvals, as a precursor to revocation

**Comment by jgarzik** [comment]
Nice to have:  URL parameters.

Visit https://pure.finance/approvals/add/VSP/VVSP to auto-fill an approval form.
